font_family JetBrainsMono Nerd Font
font_size 12.5

background_opacity 0.88
dynamic_background_opacity yes

window_padding_width 14
hide_window_decorations yes

cursor_shape beam
cursor_beam_thickness 1.5

scrollback_lines 10000
enable_audio_bell no

tab_bar_style powerline
tab_powerline_style slanted

include ~/.local/state/caelestia/theme/kitty.conf
